tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "kylef/formulae"
brew "git"
brew "go"
brew "ripgrep"
brew "rustup-init"
brew "zplug", args: ["HEAD"]
brew "kylef/formulae/swiftenv"
cask "docker"
cask "visual-studio-code"
